FROM python:3.8 as base

ENV POETRY_VIRTUALENVS_CREATE false
RUN pip install --no-cache-dir poetry

COPY ./common /app/common
COPY ./auth /app/auth/

WORKDIR /app/auth

RUN poetry install -E migrations --no-dev

FROM base as app
ENTRYPOINT ["python", "-m", "auth"]

FROM base as migrations
ENTRYPOINT ["alembic", "upgrade", "head"]
